### ISSUE TITLE
Fresh install produces: SyntaxError: Unexpected token = (line:5)

### ISSUE THREAD

**Issue by longmover** [JasonBSteele/node-red-contrib-geniushub#1]
A fresh install of node red using docker causes the above error to show in the pallete.

[https://imgur.com/G5ernSG](https://imgur.com/G5ernSG)

Previously running fine on a Pi 4

Log shows:
[info] - node-red-contrib-geniushub:geniushub-service : SyntaxError: Unexpected token = (line:5)
[info] - node-red-contrib-geniushub:geniushub-whole-house : SyntaxError: Unexpected token =
[info] - node-red-contrib-geniushub:geniushub-zone : SyntaxError: Unexpected token =

Apologies if this isn't the correct way to report, i am new to this!

**Comment by JasonBSteele** [comment]
Hi, this is likely to be caused by the older version of Node,js (v10) rather than the recommended v12.

These two links may help with understanding the relationship between Node Red and Node.js:
https://nodered.org/docs/faq/node-versions
https://nodered.org/about/releases/

I believe if you use the container with the tag `latest-12`  you will be okay:
https://hub.docker.com/layers/nodered/node-red/latest-12/images/sha256-1f1dcb7277149a2f9b840cc91bfb5ef1c12a30b5a71df1ffb7c26525e6c13a5a?context=explore

I don't know why Node Red says that Node.js v12 is recommended, but then not add it to the default container.

**Comment by longmover** [comment]
> 
> 
> Hi, this is likely to be caused by the older version of Node,js (v10) rather than the recommended v12.
> 
> These two links may help with understanding the relationship between Node Red and Node.js:
> https://nodered.org/docs/faq/node-versions
> https://nodered.org/about/releases/
> 
> I believe if you use the container with the tag `latest-12` you will be okay:
> https://hub.docker.com/layers/nodered/node-red/latest-12/images/sha256-1f1dcb7277149a2f9b840cc91bfb5ef1c12a30b5a71df1ffb7c26525e6c13a5a?context=explore
> 
> I don't know why Node Red says that Node.js v12 is recommended, but then not add it to the default container.

Spot on, works fine on a new docker instance using latest-12, thanks!

**Comment by JasonBSteele** [comment]
That's great! Thanks for letting me know.
